#!/bin/sh
# This script is a fork of https://github.com/excelsiord/docker-dropbox

# Set UID/GID if not provided with enviromental variable(s).
if [ -z "$DBOX_UID" ]; then
	DBOX_UID=$(cat /etc/passwd | grep dropbox | cut -d: -f3)
	echo "DBOX_UID (user id) variable not specified, defaulting to $DBOX_UID.."
fi

if [ -z "$DBOX_GID" ]; then
	DBOX_GID=$(cat /etc/group | grep dropbox | cut -d: -f3)
	echo "DBOX_GID (group id) variable not specified, defaulting to $DBOX_GID.."
fi

# Look for existing group, if not found create dropbox with specified GID.
FIND_GROUP=$(grep ":$DBOX_GID:" /etc/group)

if [ -z "$FIND_GROUP" ]; then
	usermod -g users dropbox
	groupdel dropbox
	groupadd -g $DBOX_GID dropbox
fi

# Set dropbox account's UID.
usermod -u $DBOX_UID -g $DBOX_GID --non-unique dropbox > /dev/null 2>&1

# Change ownership to dropbox account on all working folders.
chown -R $DBOX_UID:$DBOX_GID /dbox

# Change permissions on Dropbox folder
chmod 755 /dbox/Dropbox

#  Dropbox did not shutdown properly? Remove files.
[ ! -e "/dbox/.dropbox/command_socket" ] || rm /dbox/.dropbox/command_socket
[ ! -e "/dbox/.dropbox/iface_socket" ]   || rm /dbox/.dropbox/iface_socket
[ ! -e "/dbox/.dropbox/unlink.db" ]      || rm /dbox/.dropbox/unlink.db
[ ! -e "/dbox/.dropbox/dropbox.pid" ]    || rm /dbox/.dropbox/dropbox.pid

echo "dropboxd($(cat /dbox/.dropbox-dist/VERSION)) started..."
umask 002
exec su dropbox -s /bin/bash -c /dbox/.dropbox-dist/dropboxd
